#!/usr/bin/perl
# Copyright 2015 Alex Woroschilow (alex.woroschilow@gmail.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/src/lib";
use Config::Simple;

sub main ($ $ $ $ $) {

	my $config  = shift;
	my $logger  = shift;
	my $server  = shift;
	my $planner = shift;
	my $worker  = shift;

	system("qsub -S /bin/bash -wd $FindBin::Bin -q \"stud.q\" $server $config $logger");
	system("qsub -S /bin/bash -wd $FindBin::Bin -q \"stud.q\" $planner $config $logger");
	system("qsub -S /bin/bash -wd $FindBin::Bin -q \"stud.q\" $worker $config $logger");

	return 0;
}

exit(
	main(
		"$FindBin::Bin/etc/vector.conf", 
		"$FindBin::Bin/etc/logger.conf",
		"$FindBin::Bin/bin/server.sh",      
		"$FindBin::Bin/bin/planner.sh",
		"$FindBin::Bin/bin/worker.sh"
	)
);
