#!/usr/bin/perl
# Copyright 2015 Alex Woroschilow (alex.woroschilow@gmail.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/src/lib";
use Config::Simple;
use ZBH::SGE;

sub main ($ $ $ $ $) {

	my $config  = shift;
	my $logger  = shift;
	my $server  = shift;
	my $planner = shift;
	my $worker  = shift;

	my $cfg = new Config::Simple($config);
	# Check is all processes already started
	# using Sug Grid Engine
	return("started") if (
		ZBH::SGE::is_background_process_sge($server)
  	);
	my $logfile   = $cfg->param("planner.logfile");
	my $keystring = "wurst-vector done";
	# Check is all tasks successfully finished
	# and there are results
	return("done") if ( 
		ZBH::SGE::is_background_process_done( $logfile, $keystring ) 
	);
	# If process not started and not finished
	# it is ready to be started  	
	return ("ready");
}

exit(
	print(
		main(
			"$FindBin::Bin/etc/vector.conf", 
			"$FindBin::Bin/etc/logger.conf",
			"$FindBin::Bin/bin/server.sh",   
			"$FindBin::Bin/bin/planner.sh",
			"$FindBin::Bin/bin/worker.sh"
		)
	)
);
